### ISSUE TITLE
Downlaoding dataset takes infinite time.

### ISSUE THREAD

**Issue by himansh123** [Wikunia/HE2LaTeX#3]
Its been hours, I have been waiting for train_images.npy to get downloaded. Cant you upload the dataset to the github?

**Comment by Wikunia** [comment]
The size of that file alone is over 1 GB and the maximal size for GitHub is 100Mb. Additionally it is not reasonable to git a file of that size. The server connection should be quite fast so I suppose it's hanging on your end.
